# Generated by Django 4.2.1 on 2023-05-06 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="PaymentVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("Income", "Income"), ("Expense", "Expense")],
                        max_length=50,
                    ),
                ),
                ("request_by", models.CharField(blank=True, max_length=50, null=True)),
                ("payee", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "cheque_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "Yonna Islamic Microfinance",
                                "Yonna Islamic Microfinance",
                            ),
                            ("Ecobank", "Ecobank"),
                            ("GT-Bank", "GT-Bank"),
                            ("Access Bank", "Access Bank"),
                            ("Trust Bank", "Trust Bank"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("item", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                ("amount", models.FloatField()),
                ("total_amount", models.FloatField()),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Audit Level", "Audit Level"),
                            ("Management Level", "Management Level"),
                            ("Final Review", "Final Review"),
                            ("Approved", "Approved"),
                            ("On Hold", "On Hold"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Cash", "Cash"),
                            ("Bank Transfer", "Bank Transfer"),
                            ("Cheque", "Cheque"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "pv_id",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default="None",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.category",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
