# Generated by Django 4.2.1 on 2023-05-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_alter_paymentvoucher_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentvoucher",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="paymentvoucher",
            name="item",
        ),
        migrations.RemoveField(
            model_name="paymentvoucher",
            name="quantity",
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_eight",
            field=models.CharField(
                blank=True, default="", max_length=120, null=True, verbose_name="Item 8"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_eight_quantity",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Quantity"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_eight_total_price",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Entry Total (D)"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_eight_unit_price",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Unit Price (D)"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_five",
            field=models.CharField(
                blank=True, default="", max_length=120, null=True, verbose_name="Item 5"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_five_quantity",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Quantity"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_five_total_price",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Entry Total (D)"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_five_unit_price",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Unit Price (D)"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_four",
            field=models.CharField(
                blank=True, default="", max_length=120, null=True, verbose_name="Item 4"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_four_quantity",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Quantity"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_four_total_price",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Entry Total (D)"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_four_unit_price",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Unit Price (D)"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_nine",
            field=models.CharField(
                blank=True, default="", max_length=120, null=True, verbose_name="Item 9"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_nine_quantity",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Quantity"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_nine_total_price",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Entry Total (D)"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_nine_unit_price",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Unit Price (D)"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_one",
            field=models.CharField(
                blank=True, default="", max_length=120, null=True, verbose_name="Item 1"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_one_quantity",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Quantity"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_one_total_price",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Entry Total (D)"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_one_unit_price",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Unit Price (D)"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_seven",
            field=models.CharField(
                blank=True, default="", max_length=120, null=True, verbose_name="Item 7"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_seven_quantity",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Quantity"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_seven_total_price",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Entry Total (D)"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_seven_unit_price",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Unit Price (D)"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_six",
            field=models.CharField(
                blank=True, default="", max_length=120, null=True, verbose_name="Item 6"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_six_quantity",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Quantity"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_six_total_price",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Entry Total (D)"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_six_unit_price",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Unit Price (D)"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_ten",
            field=models.CharField(
                blank=True,
                default="",
                max_length=120,
                null=True,
                verbose_name="Item 10",
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_ten_quantity",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Quantity"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_ten_total_price",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Entry Total (D)"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_ten_unit_price",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Unit Price (D)"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_three",
            field=models.CharField(
                blank=True, default="", max_length=120, null=True, verbose_name="Item 3"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_three_quantity",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Quantity"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_three_total_price",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Entry Total (D)"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_three_unit_price",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Unit Price (D)"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_two",
            field=models.CharField(
                blank=True, default="", max_length=120, null=True, verbose_name="Item 2"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_two_quantity",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Quantity"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_two_total_price",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Entry Total (D)"
            ),
        ),
        migrations.AddField(
            model_name="paymentvoucher",
            name="item_two_unit_price",
            field=models.FloatField(
                blank=True, default=0, null=True, verbose_name="Unit Price (D)"
            ),
        ),
    ]
