# Generated by Django 4.2.1 on 2023-05-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_remove_paymentvoucher_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentvoucher",
            name="total_amount",
            field=models.FloatField(default=0),
        ),
    ]
