# Generated by Django 4.2.1 on 2023-06-23 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_company_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_eight",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Item 8"
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_eight_quantity",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_eight_total_price",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Entry Total (D)",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_eight_unit_price",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Unit Price (D)",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_five",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Item 5"
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_five_quantity",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_five_total_price",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Entry Total (D)",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_five_unit_price",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Unit Price (D)",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_four",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Item 4"
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_four_quantity",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_four_total_price",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Entry Total (D)",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_four_unit_price",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Unit Price (D)",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_nine",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Item 9"
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_nine_quantity",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_nine_total_price",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Entry Total (D)",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_nine_unit_price",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Unit Price (D)",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_one",
            field=models.CharField(max_length=120, verbose_name="Item 1"),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_seven",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Item 7"
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_seven_quantity",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_seven_total_price",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Entry Total (D)",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_seven_unit_price",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Unit Price (D)",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_six",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Item 6"
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_six_quantity",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_six_total_price",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Entry Total (D)",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_six_unit_price",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Unit Price (D)",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_ten",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Item 10"
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_ten_quantity",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_ten_total_price",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Entry Total (D)",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_ten_unit_price",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Unit Price (D)",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_three",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Item 3"
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_three_quantity",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_three_total_price",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Entry Total (D)",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_three_unit_price",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Unit Price (D)",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_two",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Item 2"
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_two_quantity",
            field=models.IntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_two_total_price",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Entry Total (D)",
            ),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="item_two_unit_price",
            field=models.FloatField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Unit Price (D)",
            ),
        ),
    ]
