# Generated by Django 4.2.1 on 2023-07-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_alter_paymentvoucher_item_eight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentvoucher",
            name="is_admin_expense",
            field=models.BooleanField(default=False),
        ),
    ]
