# Generated by Django 4.2.1 on 2023-05-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_alter_paymentvoucher_item_eight_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentvoucher",
            name="account_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="status",
            field=models.CharField(
                choices=[
                    ("Accounts Desk", "Accounts Desk"),
                    ("Audit Level", "Audit Level"),
                    ("Management Level", "Management Level"),
                    ("Final Review", "Final Review"),
                    ("Approved", "Approved"),
                    ("On Hold", "On Hold"),
                ],
                max_length=50,
            ),
        ),
    ]
