# Generated by Django 4.2.1 on 2023-07-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_paymentvoucher_is_admin_expense"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentvoucher",
            old_name="request_by",
            new_name="received_by",
        ),
        migrations.AlterField(
            model_name="paymentvoucher",
            name="bank_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Access Bank", "Access Bank"),
                    ("Ecobank", "Ecobank"),
                    ("GT-Bank", "GT-Bank"),
                    ("Trust Bank", "Trust Bank"),
                    ("Yonna Islamic Microfinance", "Yonna Islamic Microfinance"),
                    ("Zenith Bank", "Zenith Bank"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
