# Generated by Django 4.2.1 on 2023-08-18 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zone_expense", "0001_initial"),
        ("tracker", "0006_rename_request_by_paymentvoucher_received_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentvoucher",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zones",
                to="zone_expense.zone",
            ),
        ),
    ]
