# Generated by Django 4.2.1 on 2023-05-15 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tracker", "0007_paymentvoucher_approved_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentvoucher",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviewed_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
