# Generated by Django 4.2.1 on 2023-05-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0008_paymentvoucher_reviewed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentvoucher",
            name="approve",
            field=models.BooleanField(default=False),
        ),
    ]
