# Generated by Django 4.2.1 on 2023-05-18 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0010_paymentvoucher_verified_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentvoucher",
            old_name="approve",
            new_name="approved",
        ),
    ]
