# Generated by Django 4.2.1 on 2023-05-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="company",
            field=models.CharField(
                choices=[
                    ("Yonna Foreign Exchange Bureau", "Yonna Foreign Exchange Bureau"),
                    ("Yonna Islamic Microfinance", "Yonna Islamic Microfinance"),
                    ("Yonna Enterprise", "Yonna Enterprise"),
                    ("Yonna Insurance", "Yonna Insurance"),
                ],
                max_length=100,
            ),
        ),
    ]
