# Generated by Django 4.2.1 on 2023-06-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_company_limit"),
        ("accounts", "0002_alter_profile_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="company",
        ),
        migrations.AddField(
            model_name="profile",
            name="company",
            field=models.ManyToManyField(
                related_name="employees", to="tracker.company"
            ),
        ),
    ]
