# Generated by Django 4.2.1 on 2023-05-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_profile_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="title",
            field=models.CharField(
                choices=[
                    ("IT", "IT"),
                    ("Accountant", "Accountant"),
                    ("Auditor", "Auditor"),
                    ("Manager", "Manager"),
                    ("CEO", "CEO"),
                ],
                max_length=50,
            ),
        ),
    ]
