# Generated by Django 4.2.1 on 2023-06-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_alter_company_limit"),
        ("accounts", "0003_remove_profile_company_profile_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="company",
            field=models.ManyToManyField(
                blank=True, related_name="employees", to="tracker.company"
            ),
        ),
    ]
