# Generated by Django 4.2.1 on 2023-08-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_role_profile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Supervisor", "Supervisor"),
                    ("IT", "IT"),
                    ("HR", "HR"),
                    ("Compliance Officer", "Compliance Officer"),
                    ("Accountant", "Accountant"),
                    ("Auditor", "Auditor"),
                    ("Manager", "Manager"),
                    ("CEO", "CEO"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
