# Generated by Django 4.2.1 on 2023-08-18 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zone_expense", "0001_initial"),
        ("accounts", "0006_alter_profile_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                default="",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="zone_expense.zone",
            ),
        ),
    ]
